apiVersion: v1
kind: Namespace
metadata:
  name: porg-ns
---
apiVersion: v1
kind: Service
metadata:
  name: porg-service
  namespace: porg-ns
  labels:
    app: porg-app
spec:
  type: ClusterIP
  selector:
    app: porg-app
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: porg-deploy
  namespace: porg-ns
  labels:
    app: porg-app
    test: test
  annotations:
    fluxcd.io/tag.example-app: semver:~1.0
    fluxcd.io/automated: 'true'
spec:
  selector:
    matchLabels:
      app: porg-app
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: porg-app
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: porg-app
        image: registry.nicronomicon.dev/porg:1.0.0
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: porg-config
  namespace: porg-ns
data:
  config.json: |
    {
      "environment" : "dev"
    }